apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: sample-app
data:
  # 単純な設定値
  app.name: "Sample Application"
  app.version: "1.0.0"
  environment: "development"
  debug: "true"
  
  # データベース設定
  database.host: "mysql-service.default.svc.cluster.local"
  database.port: "3306"
  database.name: "sampledb"
  
  # アプリケーション設定ファイル
  application.properties: |
    server.port=8080
    server.servlet.context-path=/api
    
    logging.level.root=INFO
    logging.level.com.example=DEBUG
    
    spring.datasource.url=jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
    # Redis設定
    redis.host=redis-service
    redis.port=6379
    redis.timeout=2000
  
  # nginx設定ファイル例
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream backend {
            server backend-service:8080;
        }
        
        server {
            listen 80;
            location / {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }