apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: sample-app
type: Opaque
data:
  # Base64エンコードされた値
  # 実際の値:
  # database.username: admin
  # database.password: secret123
  # api.key: your-secret-api-key
  # jwt.secret: jwt-super-secret-key
  database.username: YWRtaW4=
  database.password: c2VjcmV0MTIz
  api.key: eW91ci1zZWNyZXQtYXBpLWtleQ==
  jwt.secret: and0LXN1cGVyLXNlY3JldC1rZXk=

---
# TLS Secret の例
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    app: sample-app
type: kubernetes.io/tls
data:
  # 実際のプロジェクトでは実際の証明書を使用
  # これはサンプル用のダミーデータです
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQU1tUWFWa3hoYkg4TUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpPV1RFTU1Bb0dBMVVFQmd3RFEyOTNjREVMTUFrR0ExVUVDZ3dDUVV4Vg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3JtS0M3QVdJK0N3TGkKdjVuSWFUUVhRZXhBcFRWUGNZWGxmMGwyVUhqY1NIaURwczVTUzNWb0dHRlBqSFpoR25yR3J3UEJ2VGw3V0tkVg==

---
# Docker Registry Secret の例
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: sample-app
type: kubernetes.io/dockerconfigjson
data:
  # docker login の認証情報をBase64エンコードしたもの
  # 実際の使用時は kubectl create secret docker-registry コマンドを推奨
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYXV0aCI6ImRYTmxjanB3WVhOemQyOXlaQT09In19fQ==