apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-app
    environment: development
spec:
  containers:
  - name: alpine-container
    image: alpine:3.18
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Hello from simple pod'; sleep 30; done"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "50m"
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  restartPolicy: Always